services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
      DATAABASE_URL: postgres://user:password@localhost:5432/db
    ports:
      - "5432:5432"
    volumes:
      - ~/.docker/volumes/postgres:/var/lib/postgresql/data
    restart: on-failure